# Sample configuration file for Mulch server (mulchd)
# Values here are defaults (except for seeds)

# Listen address (no IP = all interfaces)
listen = ":8585"

# URI libvirt will use to contact the hypervisor
libvirt_uri = "qemu:///system"

# Storage path for libvirt disk images and "seeds" (Linux distributions)
# real world example: /srv/mulch
storage_path = "./var/storage"

# Mulch server (small) databases
# real world example: /var/lib/mulch
data_path = "./var/data"

# Name prefix for Mulch VMs in libirt (so we don't collide with
# some existing VMs)
vm_prefix = "mulch-"

# This user will be created with VMs as a sudoers, and used for
# control and command of the VM by Mulch
mulch_super_user = "admin"

# SSH key for 'mulch_super_user'
# No passphrase support yet
# tip : ssh-keygen -b 4096 -C "admin@vms" -N "" -f path_to_new_key/mulch
# Mulch may generate by itself in the future, we'll see.
mulch_ssh_private_key = ""
mulch_ssh_public_key = ""

# Sample seeds
[[seed]]
name = "debian_9"
current_url = "http://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2"
as = "debian-9-openstack-amd64.qcow2"

[[seed]]
name = "centos_7"
current_url = "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
as = "centos-7-x86_64.qcow2"

[[seed]]
name = "ubuntu_1810"
current_url = "http://cloud-images.ubuntu.com/cosmic/current/cosmic-server-cloudimg-amd64.img"
as = "ubuntu-1810-amd64.qcow2"
