#cloud-config

# Cloud Init configuration file
# https://cloudinit.readthedocs.io/en/latest/topics/format.html#cloud-config-data

#password: test
#chpasswd: {expire: False}
#ssh_pwauth: True

package_upgrade: $_PACKAGE_UPGRADE
package_reboot_if_required: $_PACKAGE_UPGRADE

# we use this call to confirm Cloud-Init success
phone_home:
  url: $_PHONE_HOME_URL

groups:
  - mulcher

users:
  - name: $_MULCH_SUPER_USER
    primary-group: mulcher
    gecos: Mulch Control and Command admin account
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
    - $_SSH_PUBKEY
  - name: $_APP_USER
    gecos: Application user account
    shell: /bin/bash
    ssh_authorized_keys:
    - $_SSH_PUBKEY

# Needed when we phone home
packages:
  - curl

write_files:
  - content: |
      [Unit]
      Description=Phone home on boot
      After=network-online.target sshd.service
      Wants=network-online.target

      [Service]
      RemainAfterExit=yes
      ExecStart=/usr/local/bin/phone_home
      User=root

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    path: /etc/systemd/system/phone_home.service

  - content: |
      #!/bin/bash
      id=$(cat /var/lib/cloud/data/instance-id)
      # will dump config on stdout
      /usr/bin/curl -s -d "dump_config=true&instance_id=$id" -X POST $_PHONE_HOME_URL
    owner: root:root
    permissions: '0755'
    path: /usr/local/bin/phone_home

  - content: |
      #!/bin/bash
      id=$(cat /var/lib/cloud/data/instance-id)
      /usr/bin/curl -fs $_HOME_URL/locked?instance_id=$id
    owner: root:root
    permissions: '0755'
    path: /usr/local/bin/is_locked

  - content: |
      # Created by Mulch, erased on rebuild (see env option in TOML file to add yours)
      $__MAIN_ENV
      $__EXTRA_ENV
    owner: root:root
    permissions: '0644'
    path: /etc/mulch.env

  - content: |
      . /etc/mulch.env
    owner: root:root
    permissions: '0644'
    path: /etc/profile.d/mulch-env.sh

runcmd:
  - [ systemctl, enable, phone_home ]

#locale:
timezone: $_TIMEZONE
ntp:
  enabled: true

#power_state:
#  mode: poweroff
#  message: Cloud-init first boot finished, rebooting.
