#!/bin/bash

# -- Run with sudo privileges
# For: Debian 9 / Ubuntu 18.10

export DEBIAN_FRONTEND="noninteractive"
sudo -E apt-get -y -qq install progress mc powerline locate man || exit $?

# Set Midnight-Commander as the default editor, and apply
# a cool setup to it
sudo update-alternatives --set editor /usr/bin/mcedit || exit $?
sudo bash -c "cat > /usr/share/mc/mc.ini" <<- EOS
[Midnight-Commander]
use_internal_edit=true
editor_edit_confirm_save=false

[Panels]
navigate_with_arrows=true
EOS
[ $? -eq 0 ] || exit $?

sualias="$_APP_USER"
sudo bash -c "cat > /etc/motd" <<- EOS

Debian GNU/Linux: $_VM_NAME (rev $_VM_REVISION)
    Generated by Mulch $_MULCH_VERSION on $_VM_INIT_DATE by $_KEY_DESC
    Switch to application user: sudo -iu $_APP_USER (alias: $sualias)

EOS
[ $? -eq 0 ] || exit $?

sudo bash -c "cat > /etc/profile.d/mulch.sh" <<- EOS
if ! shopt -oq posix; then
  alias $sualias="sudo -iu $_APP_USER"
  alias ll="ls -la --color"
  alias e="mcedit"
fi
EOS
[ $? -eq 0 ] || exit $?

sudo bash -c "cat > /etc/profile.d/powerline.sh" <<- EOS
if ! shopt -oq posix; then
  if [ -f /usr/share/powerline/bindings/bash/powerline.sh ]; then
    . /usr/share/powerline/bindings/bash/powerline.sh
  fi
fi
EOS
[ $? -eq 0 ] || exit $?

# remove public access for home directories
sudo chmod o= /home/*/ /etc/skel || exit $?

# add a "open" action (see "do" command) if there's any domain defined
if [ -n "$_DOMAIN_FIRST" ]; then
    echo "_MULCH_ACTION_NAME=open"
    echo "_MULCH_ACTION_SCRIPT=https://raw.githubusercontent.com/OnitiFR/mulch/master/scripts/actions/open.sh"
    echo "_MULCH_ACTION_USER=app"
    echo "_MULCH_ACTION_DESCRIPTION=Open VM first domain in the browser"
    echo "_MULCH_ACTION=commit"
fi
