#!/bin/bash

# -- Run with sudo privileges
# For: Debian 9+ / Ubuntu 18.04+

# You import port 2049 from a NFS server, ex:
# ports = [
#    "2049/tcp<-@group",
# ]

# You must also define NFS4_MOUNT, the path where
# the server root will be mounted (directory will
# be created by the script)


if [ -z "$NFS4_MOUNT" ]; then
    >&2 echo "need NFS4_MOUNT env var"
    exit 1
fi

if [ -z "$_2049_TCP" ]; then
    >&2 echo "you must import port tcp/2049 from a NFS server"
    exit 1
fi

sudo mkdir -p "$NFS4_MOUNT" || exit $?
sudo chown "$_APP_USER:$_APP_USER" "$NFS4_MOUNT" || exit $?

export DEBIAN_FRONTEND="noninteractive"

sudo apt-get -y -qq install nfs-common || exit $?

sudo bash -c "cat >> /etc/fstab" <<- EOS
# (added by deb-nfs4-client.sh)
$_MULCH_PROXY_IP:/	$NFS4_MOUNT	nfs4	proto=tcp,timeo=100,port=$_2049_TCP 0 2
EOS
[ $? -eq 0 ] || exit $?

echo "mounting NFS filesystems"
sudo mount -a || exit $?


mkdir -p $HOME/bin || exit $?
cat <<'EOS' > $HOME/bin/nfs-monitor.sh
#!/bin/bash
cd $HOME
. /etc/mulch.env

if ! grep -q "$NFS4_MOUNT" /proc/mounts; then
    logger "NFS4 mount is not present, trying to mount"
    sudo mount -a > /dev/null
    exit 0
fi

sudo stat -t "$NFS4_MOUNT" > /dev/null
if [ $? -ne 0 ]; then
    logger "NFS4 mount is not available, trying to remount"
    sudo umount -lf "$NFS4_MOUNT" > /dev/null
    sudo mount -a > /dev/null
fi
EOS
[ $? -eq 0 ] || exit $?

chmod +x $HOME/bin/nfs-monitor.sh || exit $?

cat <<'EOS' | crontab
# m h  dom mon dow   command
# Generated by prepare/blank-app.sh Mulch script
* * * * * $HOME/bin/nfs-monitor.sh
EOS
[ $? -eq 0 ] || exit $?
