#!/bin/bash

# Run as admin user
# 'do action' script for Adminer auto-login on deb-php-pgsql.sh based VM

# Drop a single-use session file in a tmpfs and let an Adminer plugin consume it.

plugin_file="/usr/share/adminer/adminer-plugins/mulch-autologin.php"
session_file="/run/mulch-adminer/session.json"
ttl=30

eval $(sudo -n grep PGSQL_PASSWORD /home/app/env) || exit $?

# auto-login plugin, refreshed on every run
sudo -n mkdir -p "$(dirname $plugin_file)" || exit $?
sudo -n tee "$plugin_file" > /dev/null <<'EOS'
<?php
/** Mulch one-shot auto-login -- generated by deb_db_adminer.sh, do not edit. */
class AdminerMulchAutologin extends Adminer\Plugin {
    const SESSION_FILE = '/run/mulch-adminer/session.json';

    function __construct() {
	if (!isset($_GET['mulch'])) {
	    return; // not for us: let Adminer proceed normally
	}
	$raw = @file_get_contents(self::SESSION_FILE);
	@unlink(self::SESSION_FILE); // single use, even if anything below fails
	$s = json_decode((string) $raw, true);
	if (!is_array($s) || $s['exp'] < time() || !hash_equals($s['token'], $_GET['mulch'])) {
	    return;
	}

	session_regenerate_id(true);
	Adminer\set_password($s['driver'], $s['server'], $s['username'], $s['password']);
	$_SESSION['db'][$s['driver']][$s['server']][$s['username']][$s['db']] = true;

	header('Location: ?' . http_build_query(array(
	    $s['driver'] => $s['server'], // Adminer reads the server from ?pgsql=127.0.0.1
	    'username'   => $s['username'],
	    'db'         => $s['db'],
	)), true, 302);
	exit;
    }
}
EOS

# single-use session: tmpfs, outside the docroot, readable by the PHP user only
sudo -n install -d -o app -g app -m 0700 "$(dirname $session_file)" || exit $?

token="$(openssl rand -hex 32)" || exit $?

printf '{"token":"%s","exp":%d,"driver":"pgsql","server":"127.0.0.1","username":"app","db":"app","password":"%s"}' \
"$token" "$(( $(date +%s) + ttl ))" "$PGSQL_PASSWORD" \
| sudo -n install -o app -g app -m 0400 /dev/stdin "$session_file" || exit $?

# drop the old mechanism, including any leftover file holding the password
sudo -n rm -rf /usr/share/adminer/login

echo "_MULCH_OPEN_URL=https://$_DOMAIN_FIRST/_sql/adminer.php?mulch=$token"

if [ "$(is_locked)" = true ]; then
    echo -e "This VM is \e[41mlocked\e[0m."
fi
