name = "centos_7_lamp"
hostname = "lamp"

seed = "centos_7"

disk_size = "8G"
ram_size = "2G"
cpu_count = 1

auto_rebuild = "daily"

prepare = [
    "admin@{core}/prepare/seeders/rh-comfort.sh",
    "admin@{core}/prepare/seeders/rh-lamp.sh",
]
