name = "ubuntu_2004_lamp"
hostname = "lamp"

seed = "ubuntu_2004"

disk_size = "8G"
ram_size = "2G"
cpu_count = 1

auto_rebuild = "daily"

prepare_prefix_url = "https://raw.githubusercontent.com/OnitiFR/mulch/master/scripts/prepare/"
prepare = [
    "admin@seeders/deb-comfort.sh",
    "admin@seeders/deb-lamp.sh",
    "app@wp-cli.sh",
]
